### ISSUE TITLE
README links to shared decks are broken

### ISSUE THREAD

**Issue by langston-barrett** [Yorwba/anki-wikidata-geography#7]
e.g., when I navigate to https://ankiweb.net/shared/info/1113166547, all I see is "This shared item is no longer available."

**Comment by Yorwba** [comment]
Thanks for pointing that out. Anki automatically deletes shared decks that aren't downloaded often enough, so 9 of the 10 shared decks I originally uploaded were removed after 3 months. Italy survived thanks to 70 downloads.

Since I had to regenerate the decks anyways after merging #6 , I've reuploaded all of them and updated the links in the README.
